# Generated by Django 4.0.8 on 2023-07-12 22:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0001_initial'),
        ('leases', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=8)),
                ('date_paid', models.DateField()),
                ('outstanding_balance', models.DecimalField(decimal_places=2, max_digits=8)),
                ('lease', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leases.lease')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant')),
            ],
        ),
    ]
