# Generated by Django 4.2.3 on 2023-08-11 10:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0002_remove_invoice_is_paid_invoice_invoice_id_and_more'),
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='lease',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='tenant',
        ),
        migrations.AddField(
            model_name='payment',
            name='invoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='invoices.invoice'),
        ),
        migrations.AddField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(choices=[('mobile', 'Mobile Money'), ('bank', 'Bank API'), ('cash', 'Cash')], default='cash', max_length=100),
        ),
        migrations.AddField(
            model_name='payment',
            name='transaction_code',
            field=models.CharField(default='X4&HJJK', max_length=16),
        ),
        migrations.AlterField(
            model_name='payment',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
    ]
