# Generated by Django 4.0.8 on 2023-07-14 10:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0008_alter_tenant_date_of_birth'),
        ('leases', '0003_lease_leased_by'),
        ('property', '0004_remove_property_total_bathrooms_and_more'),
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='description',
            field=models.CharField(choices=[('rent_installment', 'Rent Installment'), ('rent_in_full', 'Rent in full')], default='test', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='payment',
            name='lease',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='leases.lease'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='tenants.tenant'),
        ),
        migrations.CreateModel(
            name='RentDeposits',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=8)),
                ('description', models.CharField(choices=[('commitment_fee', 'Commitment Fee'), ('deposit_in_full', 'Deposit in full')], max_length=100)),
                ('date_paid', models.DateField()),
                ('outstanding_balance', models.DecimalField(decimal_places=2, max_digits=8)),
                ('property_unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deposits', to='property.units')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deposits', to='tenants.tenant')),
            ],
        ),
    ]
