# Generated by Django 4.2.3 on 2023-08-15 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_remove_payment_lease_remove_payment_tenant_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='batch_id',
            field=models.CharField(default='202300002345', max_length=100),
        ),
    ]
