# Generated by Django 4.0.8 on 2023-07-14 18:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leases', '0003_lease_leased_by'),
        ('tenants', '0010_alter_tenant_date_of_birth'),
        ('payments', '0002_payment_description_alter_payment_lease_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Payment',
            new_name='RentPayment',
        ),
    ]
