# Generated by Django 4.2.3 on 2023-08-15 20:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_payment_batch_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='batch_id',
        ),
    ]
