# Generated by Django 4.2.3 on 2023-10-06 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[('1', 'Owner'), ('2', 'Agent'), ('3', 'Staff'), ('4', 'Tenant')], max_length=1),
        ),
    ]
