# Generated by Django 4.0.8 on 2023-07-16 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_alter_customuser_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[(1, 'Admin'), (2, 'Agent'), (3, 'Tenant'), (4, 'Staff')], default=1, max_length=1),
        ),
    ]
