# Generated by Django 4.0.8 on 2023-07-17 00:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_alter_customuser_user_type'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Admin',
        ),
    ]
