# Generated by Django 4.2.3 on 2023-08-10 21:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('property', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Setup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(default='logo/default.png', upload_to='logo/')),
                ('support_reply_email_name', models.CharField(blank=True, default='ICT Helpdesk', max_length=255, null=True)),
                ('support_reply_email', models.EmailField(blank=True, default='titusowuor30@gmail.com', max_length=255, null=True)),
                ('email_password', models.CharField(blank=True, default='xdofqrtncuimlewm', max_length=255, null=True)),
                ('email_port', models.IntegerField(blank=True, default=587, null=True)),
                ('email_backed', models.CharField(blank=True, default='smtp', max_length=100, null=True)),
                ('email_host', models.CharField(blank=True, default='smtp.gmail.com', max_length=255, null=True)),
                ('fail_silently', models.BooleanField(blank=True, default=True, null=True)),
                ('use_tls', models.BooleanField(blank=True, default=True, null=True)),
                ('code_place_holders', models.TextField(blank=True, max_length=25000, null=True)),
            ],
            options={
                'verbose_name_plural': 'Site Setup',
            },
        ),
        migrations.CreateModel(
            name='SiteConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.SlugField()),
                ('value', models.CharField(max_length=200)),
                ('config_id', models.IntegerField(default=1)),
                ('picked', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.CharField(default='Engineer, EAT Steel EAC', help_text='Enter profession and position separated by comma', max_length=100)),
                ('rating', models.CharField(choices=[('1', 1), ('2', 2), ('3', 3), ('4', 4), ('5', 5)], default='5', max_length=1)),
                ('content', tinymce.models.HTMLField()),
                ('published', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('property', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='property.property')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='testimonials', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'testimonials',
                'db_table': 'testimonials',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_name', models.CharField(max_length=100)),
                ('service_img_or_icon', models.ImageField(blank=True, null=True, upload_to='services')),
                ('content', tinymce.models.HTMLField()),
                ('published', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='property.property')),
            ],
            options={
                'verbose_name_plural': 'Services',
                'db_table': 'services',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', tinymce.models.HTMLField()),
                ('published', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='property.property')),
            ],
            options={
                'verbose_name_plural': 'about content',
                'db_table': 'about_content',
                'managed': True,
            },
        ),
    ]
