# Generated by Django 5.1.7 on 2025-11-20 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='setup',
            name='mpesa_business_short_code',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='setup',
            name='mpesa_callback_url',
            field=models.URLField(blank=True, default='https://example.com/payments/mpesa/callback/', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='setup',
            name='mpesa_consumer_key',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='setup',
            name='mpesa_consumer_secret',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='setup',
            name='mpesa_passkey',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='setup',
            name='support_reply_email',
            field=models.EmailField(blank=True, default='bengomallke@gmail.com', max_length=255, null=True),
        ),
    ]
