# Generated by Django 4.0.8 on 2023-07-16 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='setup',
            name='code_place_holders',
            field=models.TextField(blank=True, max_length=25000, null=True),
        ),
        migrations.AddField(
            model_name='setup',
            name='email_backed',
            field=models.CharField(blank=True, default='smtp', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='setup',
            name='email_host',
            field=models.CharField(blank=True, default='smtp.gmail.com', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='setup',
            name='email_password',
            field=models.CharField(blank=True, default='xdofqrtncuimlewm', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='setup',
            name='email_port',
            field=models.IntegerField(blank=True, default=587, null=True),
        ),
        migrations.AddField(
            model_name='setup',
            name='fail_silently',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
        migrations.AddField(
            model_name='setup',
            name='support_reply_email',
            field=models.EmailField(blank=True, default='titusowuor30@gmail.com', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='setup',
            name='support_reply_email_name',
            field=models.CharField(blank=True, default='ICT Helpdesk', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='setup',
            name='use_tls',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
    ]
