# Generated by Django 4.2.5 on 2025-11-20 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_setup_mpesa_business_short_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='setup',
            name='mpesa_environment',
            field=models.CharField(blank=True, choices=[('sandbox', 'Sandbox (Testing)'), ('production', 'Production (Live)')], default='sandbox', help_text="Select 'Sandbox' for testing with test credentials, or 'Production' for live transactions.", max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='setup',
            name='email_backed',
            field=models.CharField(blank=True, default='smtp', help_text="Email backend type. Usually 'smtp' for SMTP servers.", max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='setup',
            name='email_host',
            field=models.CharField(blank=True, default='smtp.gmail.com', help_text='SMTP server hostname. Gmail: smtp.gmail.com | Outlook: smtp-mail.outlook.com | Custom: your-domain.com', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='setup',
            name='email_password',
            field=models.CharField(blank=True, default='xdofqrtncuimlewm', help_text='Email password or App Password. For Gmail: Generate App Password from Google Account > Security > 2-Step Verification > App Passwords', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='setup',
            name='email_port',
            field=models.IntegerField(blank=True, default=587, help_text='SMTP port: 587 (TLS) or 465 (SSL). Default: 587 for Gmail.', null=True),
        ),
        migrations.AlterField(
            model_name='setup',
            name='fail_silently',
            field=models.BooleanField(blank=True, default=True, help_text="If True, email errors won't raise exceptions (useful for production).", null=True),
        ),
        migrations.AlterField(
            model_name='setup',
            name='mpesa_business_short_code',
            field=models.CharField(blank=True, help_text='Mpesa Business Short Code (Paybill/Till). Sandbox: 174379 | Production: Your registered Paybill/Till number.', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='setup',
            name='mpesa_callback_url',
            field=models.URLField(blank=True, default='https://example.com/payments/mpesa/callback/', help_text='Public URL where Mpesa will send payment callbacks. Must be HTTPS and publicly accessible. Use ngrok for local testing: https://your-ngrok-url.ngrok.io/payments/mpesa/callback/', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='setup',
            name='mpesa_consumer_key',
            field=models.CharField(blank=True, help_text='Mpesa Daraja API Consumer Key. Sandbox: Get from https://developer.safaricom.co.ke | Production: From your Safaricom Business account.', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='setup',
            name='mpesa_consumer_secret',
            field=models.CharField(blank=True, help_text='Mpesa Daraja API Consumer Secret. Sandbox: Get from https://developer.safaricom.co.ke | Production: From your Safaricom Business account.', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='setup',
            name='mpesa_passkey',
            field=models.CharField(blank=True, help_text='Mpesa Daraja API Passkey (Lipa na Mpesa Online Passkey). Sandbox: Get from https://developer.safaricom.co.ke | Production: From your Safaricom Business account.', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='setup',
            name='support_reply_email',
            field=models.EmailField(blank=True, default='bengomallke@gmail.com', help_text='Email address used to send notifications. For Gmail, use an App Password (not your regular password).', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='setup',
            name='support_reply_email_name',
            field=models.CharField(blank=True, default='ICT Helpdesk', help_text="Display name for email sender (e.g., 'Real Estate Admin')", max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='setup',
            name='use_tls',
            field=models.BooleanField(blank=True, default=True, help_text='Enable TLS encryption for SMTP. Required for Gmail (port 587).', null=True),
        ),
    ]
