# Generated by Django 4.0.8 on 2023-07-22 05:34

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_testimonial'),
    ]

    operations = [
        migrations.AddField(
            model_name='testimonial',
            name='rating',
            field=models.CharField(choices=[('1', 1), ('2', 2), ('3', 3), ('4', 4), ('5', 5)], default='5', max_length=1),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='content',
            field=tinymce.models.HTMLField(),
        ),
    ]
