# Generated by Django 4.0.8 on 2023-07-22 07:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0010_alter_units_description'),
        ('core', '0005_services_about'),
    ]

    operations = [
        migrations.AddField(
            model_name='testimonial',
            name='property',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='property.property'),
        ),
    ]
