# Generated by Django 4.0.8 on 2023-07-22 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_testimonial_property'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfig',
            name='config_id',
            field=models.IntegerField(default=1),
        ),
    ]
