# Generated by Django 4.0.8 on 2023-07-22 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_siteconfig_config_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfig',
            name='picked',
            field=models.BooleanField(default=False),
        ),
    ]
