# Generated by Django 4.0.8 on 2023-07-22 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_siteconfig_picked'),
    ]

    operations = [
        migrations.AddField(
            model_name='testimonial',
            name='designation',
            field=models.CharField(default='Engineer, EAT Steel EAC', help_text='Enter profession and position separated by comma', max_length=100),
        ),
    ]
