# Generated by Django 4.2.3 on 2023-08-11 11:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0002_remove_invoice_is_paid_invoice_invoice_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='due_date',
            field=models.DateField(default=datetime.datetime(2023, 8, 16, 14, 43, 37, 124990)),
        ),
    ]
