# Generated by Django 4.2.3 on 2023-08-15 20:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0003_invoice_balance_alter_invoice_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='due_date',
            field=models.DateField(default=datetime.datetime(2023, 8, 20, 23, 39, 40, 124338)),
        ),
    ]
