# Generated by Django 4.2.3 on 2023-08-15 20:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0004_alter_invoice_due_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='due_date',
            field=models.DateField(default=datetime.datetime(2023, 8, 20, 23, 48, 28, 259017)),
        ),
    ]
