# Generated by Django 4.2.3 on 2023-10-06 06:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0006_alter_invoice_due_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='due_date',
            field=models.DateField(default=datetime.datetime(2023, 10, 11, 9, 11, 29, 887738)),
        ),
    ]
