<<<<<<< Updated upstream
# Generated by Django 5.1.7 on 2025-03-11 17:29
=======
# Generated by Django 5.1.7 on 2025-03-18 20:12
>>>>>>> Stashed changes

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0009_alter_invoice_due_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='due_date',
<<<<<<< Updated upstream
            field=models.DateField(default=datetime.datetime(2025, 3, 16, 20, 29, 57, 555894)),
=======
            field=models.DateField(default=datetime.datetime(2025, 3, 23, 23, 12, 7, 722839)),
>>>>>>> Stashed changes
        ),
    ]
