# Generated by Django 5.1.7 on 2025-03-20 13:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0011_alter_invoice_due_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='due_date',
            field=models.DateField(default=datetime.datetime(2025, 3, 25, 16, 58, 25, 121474)),
        ),
    ]
