# Generated by Django 4.0.8 on 2023-07-18 10:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='staff',
            options={'verbose_name_plural': 'Staff'},
        ),
        migrations.AlterModelOptions(
            name='staffsalary',
            options={'verbose_name_plural': 'Staff Salary Details'},
        ),
        migrations.RemoveField(
            model_name='staffsalary',
            name='month',
        ),
        migrations.RemoveField(
            model_name='staffsalary',
            name='year',
        ),
        migrations.AddField(
            model_name='staff',
            name='created_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='staff_ower', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterModelTable(
            name='staff',
            table='staff',
        ),
        migrations.AlterModelTable(
            name='staffsalary',
            table='staff_salary',
        ),
        migrations.CreateModel(
            name='StaffSalaryPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.PositiveIntegerField()),
                ('year', models.PositiveIntegerField()),
                ('net_pay', models.DecimalField(decimal_places=2, max_digits=10)),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salary_pay_details', to='staff.staff')),
            ],
            options={
                'verbose_name_plural': 'Staff Payment Details',
                'db_table': 'staff_payments',
            },
        ),
    ]
