# Generated by Django 4.0.8 on 2023-07-19 07:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0002_alter_staff_options_alter_staffsalary_options_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StaffSalaryPayment',
        ),
    ]
