# Generated by Django 4.0.8 on 2023-07-19 12:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0003_delete_staffsalarypayment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staffsalary',
            name='allowances',
        ),
        migrations.RemoveField(
            model_name='staffsalary',
            name='basic_salary',
        ),
        migrations.RemoveField(
            model_name='staffsalary',
            name='deductions',
        ),
        migrations.AlterField(
            model_name='staffsalary',
            name='net_salary',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.CreateModel(
            name='Earning',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='earnings', to='staff.staff')),
            ],
        ),
        migrations.CreateModel(
            name='Deduction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deductions', to='staff.staff')),
            ],
        ),
        migrations.AddField(
            model_name='staffsalary',
            name='earnings',
            field=models.ManyToManyField(to='staff.earning'),
        ),
        migrations.AddField(
            model_name='staffsalary',
            name='deductions',
            field=models.ManyToManyField(to='staff.deduction'),
        ),
    ]
