# Generated by Django 4.0.8 on 2023-07-19 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0004_remove_staffsalary_allowances_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deduction',
            name='staff',
        ),
        migrations.RemoveField(
            model_name='earning',
            name='staff',
        ),
    ]
