# Generated by Django 4.0.8 on 2023-07-19 13:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0005_remove_deduction_staff_remove_earning_staff'),
    ]

    operations = [
        migrations.AddField(
            model_name='deduction',
            name='staff',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='deductions', to='staff.staff'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='earning',
            name='staff',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='earnings', to='staff.staff'),
            preserve_default=False,
        ),
    ]
