# Generated by Django 4.0.8 on 2023-07-12 22:02

import datetime
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=10)),
                ('date_of_birth', models.DateField(default=datetime.datetime(2023, 7, 12, 22, 2, 58, 358871, tzinfo=utc), max_length=200)),
                ('National_ID', models.CharField(default='899338', max_length=10)),
                ('date_of_registration', models.DateField(default=django.utils.timezone.now)),
                ('mobile_number', models.CharField(blank=True, max_length=13, validators=[django.core.validators.RegexValidator(message="Entered mobile number isn't in a right format!", regex='^(?:\\+254|0)[17]\\d{8}$')])),
                ('others', models.TextField(blank=True, default='N/A', null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tenants', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Tenant_Kin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('phone', models.CharField(blank=True, max_length=13, validators=[django.core.validators.RegexValidator(message="Entered mobile number isn't in a right format!", regex='^(?:\\+254|0)[17]\\d{8}$')])),
                ('relation', models.CharField(max_length=100)),
                ('emergency_name', models.CharField(max_length=100)),
                ('emergency_phone_number', models.CharField(blank=True, max_length=13, validators=[django.core.validators.RegexValidator(message="Entered mobile number isn't in a right format!", regex='^(?:\\+254|0)[17]\\d{8}$')])),
                ('emergency_email', models.EmailField(max_length=100)),
                ('emergency_adress', models.TextField(max_length=500)),
                ('emergency_physical_adress', models.TextField(max_length=500)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kins', to='tenants.tenant')),
            ],
            options={
                'verbose_name_plural': 'Kins',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Tenant_Employment_Details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employment_status', models.CharField(choices=[('employed', 'employed'), ('unemployed', 'unemployed'), ('selfemployed', 'selfemployed')], max_length=50)),
                ('emplyment_title', models.CharField(max_length=100)),
                ('employment_postion', models.CharField(max_length=100)),
                ('employer_contact', models.CharField(blank=True, max_length=13, validators=[django.core.validators.RegexValidator(message="Entered mobile number isn't in a right format!", regex='^(?:\\+254|0)[17]\\d{8}$')])),
                ('employer_email', models.EmailField(max_length=100)),
                ('employer_address', models.TextField(max_length=500)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employments', to='tenants.tenant')),
            ],
            options={
                'verbose_name_plural': 'Employment Details',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Tenant_Business_Details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_name', models.CharField(max_length=100)),
                ('license_number', models.CharField(max_length=100)),
                ('tax_id', models.CharField(max_length=100)),
                ('business_email', models.EmailField(max_length=100)),
                ('business_address', models.TextField(max_length=500)),
                ('business_description', models.TextField(max_length=500)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='businesses', to='tenants.tenant')),
            ],
            options={
                'verbose_name_plural': 'Business Details',
                'managed': True,
            },
        ),
    ]
