# Generated by Django 4.0.8 on 2023-07-12 22:51

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenant',
            name='date_of_birth',
            field=models.DateField(default=datetime.datetime(2023, 7, 12, 22, 51, 13, 142782, tzinfo=utc), max_length=200),
        ),
    ]
