# Generated by Django 4.2.3 on 2023-08-11 10:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenant',
            name='date_of_birth',
            field=models.DateField(default=datetime.datetime(2023, 8, 11, 10, 21, 15, 188961, tzinfo=datetime.timezone.utc), max_length=200),
        ),
    ]
