# Generated by Django 4.2.3 on 2023-08-11 11:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0002_alter_tenant_date_of_birth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenant',
            name='date_of_birth',
            field=models.DateField(default=datetime.datetime(2023, 8, 11, 11, 43, 37, 124990, tzinfo=datetime.timezone.utc), max_length=200),
        ),
    ]
