# Generated by Django 4.2.3 on 2023-08-15 20:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0004_alter_tenant_date_of_birth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenant',
            name='date_of_birth',
            field=models.DateField(default=datetime.datetime(2023, 8, 15, 20, 48, 28, 242822, tzinfo=datetime.timezone.utc), max_length=200),
        ),
    ]
