# Generated by Django 4.0.8 on 2023-07-14 07:53

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0006_tenant_created_by_alter_tenant_date_of_birth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenant',
            name='date_of_birth',
            field=models.DateField(default=datetime.datetime(2023, 7, 14, 7, 53, 17, 790501, tzinfo=utc), max_length=200),
        ),
    ]
