# Generated by Django 4.2.3 on 2023-10-06 06:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0007_alter_tenant_date_of_birth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenant',
            name='date_of_birth',
            field=models.DateField(default=datetime.datetime(2023, 10, 6, 6, 15, 47, 217113, tzinfo=datetime.timezone.utc), max_length=200),
        ),
    ]
