<<<<<<< Updated upstream
<<<<<<< Updated upstream
# Generated by Django 5.1.7 on 2025-03-11 17:29
=======
# Generated by Django 5.1.7 on 2025-03-18 20:12
>>>>>>> Stashed changes
=======
# Generated by Django 5.1.7 on 2025-03-18 20:12
>>>>>>> Stashed changes

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0009_alter_tenant_date_of_birth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenant',
            name='date_of_birth',
<<<<<<< Updated upstream
<<<<<<< Updated upstream
            field=models.DateField(default=datetime.datetime(2025, 3, 11, 17, 29, 57, 553903, tzinfo=datetime.timezone.utc), max_length=200),
=======
            field=models.DateField(default=datetime.datetime(2025, 3, 18, 20, 12, 7, 718842, tzinfo=datetime.timezone.utc), max_length=200),
>>>>>>> Stashed changes
=======
            field=models.DateField(default=datetime.datetime(2025, 3, 18, 20, 12, 7, 718842, tzinfo=datetime.timezone.utc), max_length=200),
>>>>>>> Stashed changes
        ),
    ]
