# Generated by Django 4.0.8 on 2023-07-14 18:18

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0009_alter_tenant_date_of_birth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenant',
            name='date_of_birth',
            field=models.DateField(default=datetime.datetime(2023, 7, 14, 18, 17, 57, 596636, tzinfo=utc), max_length=200),
        ),
    ]
