# Generated by Django 5.1.7 on 2025-03-18 21:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0010_alter_tenant_date_of_birth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenant',
            name='date_of_birth',
            field=models.DateField(default=datetime.datetime(2025, 3, 18, 21, 50, 50, 684013, tzinfo=datetime.timezone.utc), max_length=200),
        ),
    ]
