# Generated by Django 5.1.7 on 2025-03-20 13:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0011_alter_tenant_date_of_birth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenant',
            name='date_of_birth',
            field=models.DateField(default=datetime.datetime(2025, 3, 20, 13, 58, 25, 118254, tzinfo=datetime.timezone.utc), max_length=200),
        ),
    ]
