# Generated by Django 5.1.7 on 2025-11-20 16:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0013_alter_tenant_date_of_birth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenant',
            name='date_of_birth',
            field=models.DateField(default=datetime.datetime(2025, 11, 20, 16, 13, 45, 944699, tzinfo=datetime.timezone.utc), max_length=200),
        ),
    ]
