# Generated by Django 4.0.8 on 2023-07-08 15:56

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('landlords', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agent',
            name='contact_number',
        ),
        migrations.RemoveField(
            model_name='agent',
            name='name',
        ),
        migrations.RemoveField(
            model_name='propertyowner',
            name='contact_number',
        ),
        migrations.AddField(
            model_name='agent',
            name='mobile_number',
            field=models.CharField(blank=True, max_length=13, validators=[django.core.validators.RegexValidator(message="Entered mobile number isn't in a right format!", regex='^(?:\\+254|0)[17]\\d{8}$')]),
        ),
        migrations.AddField(
            model_name='agent',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='agents', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='propertyowner',
            name='mobile_number',
            field=models.CharField(blank=True, max_length=13, validators=[django.core.validators.RegexValidator(message="Entered mobile number isn't in a right format!", regex='^(?:\\+254|0)[17]\\d{8}$')]),
        ),
        migrations.AddField(
            model_name='propertyowner',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='owners', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
