# Generated by Django 4.0.8 on 2023-07-08 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('landlords', '0002_remove_agent_contact_number_remove_agent_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='propertyowner',
            name='name',
        ),
    ]
