# Generated by Django 4.0.8 on 2023-07-11 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landlords', '0005_alter_agent_owner_alter_agent_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='ID_Snapshot',
            field=models.ImageField(blank=True, null=True, upload_to='owners/documents/'),
        ),
        migrations.AddField(
            model_name='agent',
            name='national_id',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='propertyowner',
            name='ID_Snapshot',
            field=models.ImageField(blank=True, null=True, upload_to='owners/documents/'),
        ),
        migrations.AddField(
            model_name='propertyowner',
            name='national_id',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
