# Generated by Django 4.2.3 on 2023-08-10 21:47

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Enquiries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('mobile_number', models.CharField(blank=True, max_length=13, validators=[django.core.validators.RegexValidator(message="Entered mobile number isn't in a right format!", regex='^(?:\\+254|0)[17]\\d{8}$')])),
                ('date', models.DateField(auto_now_add=True)),
                ('message', tinymce.models.HTMLField()),
                ('read', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notice_type', models.CharField(choices=[('vacate', 'Vacate Notice'), ('mainatainance', 'Maintainace'), ('welcome', 'Welcome Notice')], max_length=100)),
                ('notify_group_of_users', models.CharField(blank=True, choices=[('1', 'Owner'), ('2', 'Agent'), ('3', 'Staff'), ('4', 'Tenant')], help_text='Leave Blank if not applicable', max_length=50, null=True)),
                ('notice_date', models.DateField()),
                ('description', tinymce.models.HTMLField(default='<h1>WELCOME NEW TENANT</h1><h4>Dear Mr./Mrs./Miss</h4>                                     <p>It is our pleasure to welcome you to your new home. We hope that you will be very happy here and will try our best to make sure that you are always satisfied.                                     <br/>Thankyou for selecting Fernbrook Apartments and we sincerely hope that you find your new home comfortable and enjoyable.                                     <br/>If we can be of any assistance to you, please let us know.                                     <br/>I can be reached at + 1(952) 210 0808 at any time. Rosemary can be reached at +1(763)458 6243.                                     <br/><br/><strong>Yours sincerely,                                     <br/>Wycliffe George/ Director</strong></p>')),
                ('reason', models.CharField(blank=True, default='Reason here', max_length=255, null=True)),
                ('read', models.BooleanField(default=False)),
                ('notify_specific_user', models.ForeignKey(blank=True, help_text='Leave Blank if not applicable', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notices', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='NoticeFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notice_date', models.DateField(auto_now_add=True)),
                ('reply', tinymce.models.HTMLField()),
                ('read', models.BooleanField(default=False)),
                ('notice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='notices.notice')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
