# Generated by Django 4.0.8 on 2023-07-16 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notices', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notice',
            name='reason',
            field=models.CharField(blank=True, default='Reason here', max_length=255, null=True),
        ),
    ]
