# Generated by Django 4.2.3 on 2023-08-15 20:39

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('notices', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notice',
            name='description',
            field=tinymce.models.HTMLField(default='<h1>WELCOME NEW TENANT</h1><h4>Dear Mr./Mrs./Miss</h4>                                     <p>It is our pleasure to welcome you to your new home. We hope that you will be very happy here and will try our best to make sure that you are always satisfied.                                     <br/>Thankyou for selecting Fernbrook Apartments and we sincerely hope that you find your new home comfortable and enjoyable.                                     <br/>If we can be of any assistance to you, please let us know.                                     <br/>For any assistance contact our system admin Mr. Felix phone\xa00769620042.                                     <br/><br/><strong>Yours sincerely,                                     <br/>Wycliffe George/ Director</strong></p>'),
        ),
    ]
