# Generated by Django 4.0.8 on 2023-07-22 06:57

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('notices', '0002_notice_reason'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enquiries',
            name='message',
            field=tinymce.models.HTMLField(),
        ),
        migrations.AlterField(
            model_name='notice',
            name='description',
            field=tinymce.models.HTMLField(),
        ),
        migrations.AlterField(
            model_name='noticefeedback',
            name='reply',
            field=tinymce.models.HTMLField(),
        ),
    ]
