# Generated by Django 4.0.8 on 2023-07-19 07:42

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffsalarypayment',
            name='date_of_pyament',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2023, 7, 19, 7, 42, 53, 201067, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
