# Generated by Django 4.0.8 on 2023-07-19 12:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0004_remove_staffsalary_allowances_and_more'),
        ('payroll', '0002_staffsalarypayment_date_of_pyament'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staffsalarypayment',
            name='allowances',
        ),
        migrations.AddField(
            model_name='staffsalarypayment',
            name='earnings',
            field=models.ManyToManyField(blank=True, to='staff.earning'),
        ),
        migrations.RemoveField(
            model_name='staffsalarypayment',
            name='deductions',
        ),
        migrations.AddField(
            model_name='staffsalarypayment',
            name='deductions',
            field=models.ManyToManyField(blank=True, to='staff.deduction'),
        ),
        migrations.AlterField(
            model_name='staffsalarypayment',
            name='staff',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='staff.staff'),
        ),
    ]
