# Generated by Django 4.0.8 on 2023-07-20 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0003_remove_staffsalarypayment_allowances_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staffsalarypayment',
            name='deductions',
        ),
        migrations.RemoveField(
            model_name='staffsalarypayment',
            name='earnings',
        ),
        migrations.AlterField(
            model_name='staffsalarypayment',
            name='net_pay',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
