# Generated by Django 4.2.3 on 2023-08-10 21:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tenants', '0001_initial'),
        ('property', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lease',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(default=django.utils.timezone.now)),
                ('end_date', models.DateField(blank=True, default=django.utils.timezone.now, null=True)),
                ('monthly_rent', models.DecimalField(decimal_places=2, default=2000, max_digits=8)),
                ('security_deposit', models.DecimalField(decimal_places=2, default=2000, max_digits=8)),
                ('is_active', models.BooleanField(default=False)),
                ('leased_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('property_unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leases', to='property.units')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leases', to='tenants.tenant')),
            ],
            options={
                'verbose_name_plural': 'Leases',
                'db_table': 'leases',
            },
        ),
        migrations.CreateModel(
            name='LeaseTerm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('late_payment_fine', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('uilities_description', models.CharField(default='Electricity,Water,Gabbage management,swimming pool,gym', max_length=500)),
                ('utilities_amount', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('term_number', models.PositiveIntegerField(default=1001)),
                ('term_description', models.TextField(default='Description here', max_length=500)),
                ('accepted', models.BooleanField(default=False)),
                ('lease', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='terms', to='leases.lease')),
            ],
            options={
                'verbose_name_plural': 'Lease Terms',
                'db_table': 'lease_terms',
            },
        ),
    ]
