# Generated by Django 4.0.8 on 2023-07-12 22:02

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lease',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(default=django.utils.timezone.now)),
                ('end_date', models.DateField(blank=True, default=django.utils.timezone.now, null=True)),
                ('monthly_rent', models.DecimalField(decimal_places=2, default=2000, max_digits=8)),
                ('security_deposit', models.DecimalField(decimal_places=2, default=2000, max_digits=8)),
                ('is_active', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'Leases',
                'db_table': 'leases',
            },
        ),
        migrations.CreateModel(
            name='LeaseTerm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('late_payment_fine', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('term_number', models.PositiveIntegerField(default=28)),
                ('term_description', models.TextField(default='Description here', max_length=500)),
                ('term_start_date', models.DateField(default=django.utils.timezone.now)),
                ('term_end_date', models.DateField(default=django.utils.timezone.now)),
                ('accepted', models.BooleanField(default=False)),
                ('lease', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='terms', to='leases.lease')),
            ],
            options={
                'verbose_name_plural': 'Lease Terms',
                'db_table': 'lease_terms',
            },
        ),
    ]
