# Generated by Django 4.0.8 on 2023-07-14 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leases', '0003_lease_leased_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaseterm',
            name='uilities_description',
            field=models.CharField(default='Electricity,Water,Gabbage management,swimming pool,gym', max_length=500),
        ),
        migrations.AddField(
            model_name='leaseterm',
            name='utilities_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AlterField(
            model_name='leaseterm',
            name='term_number',
            field=models.PositiveIntegerField(default=1001),
        ),
    ]
