# Generated by Django 4.0.8 on 2023-07-14 20:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leases', '0004_leaseterm_uilities_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leaseterm',
            name='term_end_date',
        ),
        migrations.RemoveField(
            model_name='leaseterm',
            name='term_start_date',
        ),
    ]
