# Generated by Django 4.0.8 on 2023-07-12 22:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('landlords', '0006_agent_id_snapshot_agent_national_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='property/images')),
            ],
            options={
                'verbose_name_plural': 'Gallery',
                'db_table': 'gallery',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Units',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='test', max_length=100)),
                ('unit_code', models.CharField(default='001', max_length=100)),
                ('description', models.TextField(default='desc', max_length=1500)),
                ('rental_price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('square_footage', models.PositiveIntegerField(default=2)),
                ('bedrooms', models.PositiveIntegerField(default=0)),
                ('bathrooms', models.PositiveIntegerField(default=0)),
                ('unit_type', models.CharField(choices=[('studio', 'Studio'), ('1br', '1 Bedroom'), ('2br', '2 Bedrooms'), ('3br', '3 Bedrooms'), ('penthouse', 'Penthouse'), ('office', 'Office Space')], max_length=20)),
                ('is_available', models.BooleanField(default=True)),
                ('images', models.ManyToManyField(blank=True, null=True, to='property.images')),
            ],
            options={
                'verbose_name_plural': 'Units',
                'db_table': 'units',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(default='addr', max_length=255)),
                ('property_type', models.CharField(choices=[('house', 'House'), ('apartment', 'Apartment'), ('condo', 'Condo'), ('townhouse', 'Townhouse'), ('commercial', 'Commercial')], default='apartment', max_length=20)),
                ('property_name', models.CharField(default='amase', max_length=255)),
                ('description', models.TextField(default='desc', max_length=1500)),
                ('amenities', models.TextField(default='amenities here', max_length=1500)),
                ('property_status', models.CharField(choices=[('available', 'Available'), ('rented', 'Rented'), ('unavailable', 'Unavailable')], default='available', max_length=20)),
                ('year_built', models.PositiveIntegerField(default=2023)),
                ('total_rooms', models.PositiveIntegerField(default=0)),
                ('total_bathrooms', models.PositiveIntegerField(default=0)),
                ('square_footage', models.PositiveIntegerField(default=0)),
                ('is_featured', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='properties', to='landlords.propertyowner')),
                ('property_images', models.ManyToManyField(blank=True, null=True, to='property.images')),
                ('units', models.ManyToManyField(blank=True, null=True, to='property.units')),
            ],
            options={
                'verbose_name_plural': 'Properties',
                'db_table': 'properties',
                'managed': True,
            },
        ),
    ]
