# Generated by Django 4.0.8 on 2023-07-12 22:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PropertyImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='property/images')),
            ],
            options={
                'verbose_name_plural': 'Property Images',
                'db_table': 'property_images',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='PropertyUnitImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='property_units/images')),
            ],
            options={
                'verbose_name_plural': 'Property Unit Images',
                'db_table': 'property_unit_images',
                'managed': True,
            },
        ),
        migrations.RemoveField(
            model_name='property',
            name='property_images',
        ),
        migrations.RemoveField(
            model_name='units',
            name='images',
        ),
        migrations.DeleteModel(
            name='Images',
        ),
        migrations.AddField(
            model_name='propertyunitimages',
            name='property_unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='property_images', to='property.units'),
        ),
        migrations.AddField(
            model_name='propertyimages',
            name='property',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='property_images', to='property.property'),
        ),
    ]
