# Generated by Django 4.2.3 on 2023-10-06 06:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='units',
        ),
        migrations.AddField(
            model_name='units',
            name='property',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='units', to='property.property'),
        ),
        migrations.AlterField(
            model_name='units',
            name='unit_type',
            field=models.CharField(choices=[('studio', 'Studio'), ('bedseater', 'BedSeater'), ('1br', '1 Bedroom'), ('2br', '2 Bedrooms'), ('3br', '3 Bedrooms'), ('penthouse', 'Penthouse'), ('office', 'Office Space')], max_length=20),
        ),
    ]
