# Generated by Django 4.0.8 on 2023-07-12 22:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0002_propertyimages_propertyunitimages_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propertyunitimages',
            name='property_unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unit_images', to='property.units'),
        ),
    ]
