# Generated by Django 4.2.3 on 2023-10-06 06:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0002_remove_property_units_units_property_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='units',
            name='property_unit_images',
        ),
    ]
