# Generated by Django 4.0.8 on 2023-07-13 08:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0003_alter_propertyunitimages_property_unit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='total_bathrooms',
        ),
        migrations.RemoveField(
            model_name='property',
            name='total_rooms',
        ),
    ]
