# Generated by Django 4.0.8 on 2023-07-21 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0004_remove_property_total_bathrooms_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='units',
            name='property_unit_images',
            field=models.ManyToManyField(blank=True, null=True, to='property.propertyunitimages'),
        ),
    ]
