# Generated by Django 4.0.8 on 2023-07-21 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0005_units_property_unit_images'),
    ]

    operations = [
        migrations.AddField(
            model_name='units',
            name='featured',
            field=models.BooleanField(default=False),
        ),
    ]
