# Generated by Django 4.0.8 on 2023-07-21 18:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0006_units_featured'),
    ]

    operations = [
        migrations.RenameField(
            model_name='units',
            old_name='featured',
            new_name='is_featured',
        ),
    ]
