# Generated by Django 4.0.8 on 2023-07-21 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0007_rename_featured_units_is_featured'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='city',
            field=models.CharField(default='Oyugis', max_length=255),
        ),
        migrations.AddField(
            model_name='property',
            name='country',
            field=models.CharField(default='Kenya', max_length=255),
        ),
    ]
