# Generated by Django 4.0.8 on 2023-07-21 20:50

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0008_property_city_property_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='amenities',
            field=tinymce.models.HTMLField(),
        ),
        migrations.AlterField(
            model_name='property',
            name='description',
            field=tinymce.models.HTMLField(),
        ),
    ]
