# Generated by Django 4.0.8 on 2023-07-21 21:17

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0009_alter_property_amenities_alter_property_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='units',
            name='description',
            field=tinymce.models.HTMLField(),
        ),
    ]
